version: '3.9'

services:
  postgres-db:
    container_name: postgres-db-dev-app
    image: postgres
    hostname: localhost
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev-app
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

#volumes:
#  postgres-data: